## boolean index

* numpy는 배열은 특정 조건에 따른 값을 배열 형태로 추출 할 수 있음
* comparison operation 함수들도 모두 사용 가능

In [2]:
import numpy as np

In [4]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [5]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [6]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [7]:
A = np.array([
    [1, 2, 6, 11, 14],
    [3, 1000, 2, -4, 8],
    [-5, -4, 1, 9, 6]
])
B = A > 5

In [8]:
B.astype(np.int)

array([[0, 0, 1, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1]])

## fancy index

* numpy는 array를 index value로 사용해서 값을 추출 할 수 있다.

In [9]:
a = np.array([2, 4, 6, 8], float)
b = np.array([3, 0, 0, 1, 2, 1, 2])
a[b]

array([8., 2., 2., 4., 6., 4., 6.])

In [10]:
a.take(b) # fancy index를 명시해 주므로 take 쓰는 것을 권장

array([8., 2., 2., 4., 6., 4., 6.])

In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([0, 0, 1])
c = np.array([1, 1, 0])
a[b, c]

array([2, 2, 3])